---
- import_playbook: ansible/playbooks/playbook.all.yml
- import_playbook: ansible/playbooks/playbook.mysql.yml
- import_playbook: ansible/playbooks/playbook.backend.yml
- import_playbook: ansible/playbooks/playbook.frontend.yml

